version: '4.0'

services:

  rhyme-php-apache:
    container_name: rhyme-php-apache
    image: php:8.2-apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rhyme-mysql
    volumes:
      - ./:/var/www
      - ./public:/var/www/html
    ports:
      - 8000:80
  
  rhyme-mysql:
    container_name: rhyme-mysql
    image: mysql
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rhyme
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345679
    ports:
      - 9906:3306
